#!/bin/bash

#set -x

PATH=/usr/sbin:/usr/bin:/sbin:/bin
TEAMS_USER=teams

# do we need to use sudo to start docker containers?
( id -Gn | grep -q docker ) || SUDO=sudo

USER_UID=$(id -u)
USER_GID=$(id -g)

XSOCK=/tmp/.X11-unix
XAUTH=/tmp/.docker.xauth

DOWNLOAD_DIR=$(xdg-user-dir DOWNLOAD)
if [ -z "${DOWNLOAD_DIR}" ]; then
    DOWNLOAD_DIR="${HOME}/Downloads"
fi;
DOCUMENTS_DIR=$(xdg-user-dir DOCUMENTS)
if [ -z "${DOCUMENTS_DIR}" ]; then
    DOCUMENTS_DIR="${HOME}/Documents"
fi;

list_commands() {
  echo ""
  echo "Launch teams using:"
  echo "  teams                        OR "
  echo "  teams-wrapper bash"
  echo ""
  exit 1
}

cleanup_stopped_teams_instances(){
  echo "Cleaning up stopped teams instances..."
  for c in $(${SUDO} docker ps -a -q)
  do
    image="$(${SUDO} docker inspect -f {{.Config.Image}} ${c})"
    if [ "${image}" == "olberger/docker-teams-linux:latest" ]; then
      running=$(${SUDO} docker inspect -f {{.State.Running}} ${c})
      if [ "${running}" != "true" ]; then
        ${SUDO} docker rm "${c}" >/dev/null
      fi
    fi
  done
}

prepare_docker_env_parameters() {
  ENV_VARS+=" --env=USER_UID=${USER_UID}"
  ENV_VARS+=" --env=USER_GID=${USER_GID}"
  ENV_VARS+=" --env=DISPLAY=unix$DISPLAY"
  ENV_VARS+=" --env=XAUTHORITY=${XAUTH}"
  ENV_VARS+=" --env=TZ=$(date +%Z)"
}

prepare_docker_volume_parameters() {
  touch ${XAUTH}
  xauth nlist :0 | sed -e 's/^..../ffff/' | xauth -f ${XAUTH} nmerge -

  if [[ -z "${TEAMS_HOME}" ]]; then
    TEAMS_HOME=${HOME} # Default directory
  else
    DOWNLOAD_DIR=${DOWNLOAD_DIR/$HOME/$TEAMS_HOME}
    DOCUMENTS_DIR=${DOCUMENTS_DIR/$HOME/$TEAMS_HOME}
    mkdir -p {$DOWNLOAD_DIR,$DOCUMENTS_DIR}

#    mkdir -p ${TEAMS_HOME}/{.config,.cache}
    mkdir -p ${TEAMS_HOME}/.config
  fi

  echo "Using TEAMS_HOME: ${TEAMS_HOME}"

#  touch ${TEAMS_HOME}/.config/zoomus.conf # create if not exists

#  VOLUMES+=" --volume=${TEAMS_HOME}/.config/zoomus.conf:/home/${TEAMS_USER}/.config/zoomus.conf"
  VOLUMES+=" --volume=${TEAMS_HOME}/.config/teams:/home/${TEAMS_USER}/.config/teams"
  VOLUMES+=" --volume=${TEAMS_HOME}/.config/Microsoft:/home/${TEAMS_USER}/.config/Microsoft"
  # VOLUMES+=" --volume=${TEAMS_HOME}/.cache/zoom:/home/${TEAMS_USER}/.cache/zoom"
  # VOLUMES+=" --volume=${TEAMS_HOME}/.zoom:/home/${TEAMS_USER}/.zoom"
  # VOLUMES+=" --volume=${DOWNLOAD_DIR}:/home/${TEAMS_USER}/Downloads"
  # VOLUMES+=" --volume=${DOCUMENTS_DIR}:/home/${TEAMS_USER}/Documents"
  VOLUMES+=" --volume=${XSOCK}:${XSOCK}"
  VOLUMES+=" --volume=${XAUTH}:${XAUTH}"
  VOLUMES+=" --volume=/run/user/${USER_UID}/pulse:/run/pulse"
}

prepare_docker_device_parameters() {
  # enumerate video devices for webcam support
  VIDEO_DEVICES=
  for device in /dev/video*
  do
    if [ -c $device ]; then
      VIDEO_DEVICES="${VIDEO_DEVICES} --device $device:$device"
    fi
  done
}

#prog=$(basename $0)
prog=$(basename bash)
exec=$(which $prog)

if [[ ${prog} == "teams-wrapper" ]]; then
  case ${1} in
    # teams)
    #   prog=${1}
    #   shift
    #   ;;
    bash)
      prog=${1}
      shift
      ;;
    *|help)
      list_commands
      exit 1
      ;;
  esac
elif [[ -n ${exec} ]]; then
    # launch host binary if it exists
    exec ${exec} $@
fi

cleanup_stopped_teams_instances
prepare_docker_env_parameters
prepare_docker_volume_parameters
prepare_docker_device_parameters

echo "Starting ${prog}..."
#${SUDO} docker run -d \
yes 'teams; while true; printf "\033c"; do sleep 10; done' | ${SUDO} docker run -it \
  ${ENV_VARS} \
  ${VIDEO_DEVICES} \
  --device /dev/dri \
  ${VOLUMES} \
  ${TEAMS_EXTRA_DOCKER_ARGUMENTS} \
  --name teams \
  olberger/docker-teams-linux:latest ${prog} $@

#>/dev/null
